
---
title: "Estimating and hypothesis testing 2 10"
author: "Jordy Taylor"
date: "Tuesday, February 10, 2015"
output: html_document
---


1. Standard Error of the Mean
  Calculate the standard error of the mean for 
  -iris sepal lengths for IRIS SETOSA
  
  setosa<-iris[iris$Species=="setosa",]
  std.err(setosa$ Sepal.Length)
[1] 0.04984957
  
  
  -iris sepal lengths for IR. VIRGINICA
  std.err(virginica$ Sepal.Length)
[1] 0.08992695

  -skull widths in female Australian possums
  
  skull<-possum[possum$sex=="f",]
> std.err(skull$skullw)
[1] 0.3917365

1.2  Confidence Intervals 
What is the 95% confidence interval for the mean Petal Length in Iris Vir?

mean-(QT*SEM)
[1] 6.738709
> mean+(QT*SEM)
[1] 6.437291
> qt(.025,49)->QT

What is the 95% confidence interval for the mean Petal Length in Iris Versicolor?


> mean(versicolor$Petal.Length)
[1] 4.26
> qt(versicolor$Petal.Length)
Error in qt(versicolor$Petal.Length) : 
  argument "df" is missing, with no default
> qt(.025,99)
[1] -1.984217
> std.err(versicolor$Petal.Length)
[1] 0.06645545
> 4.26-(-1.984217*.06645545)
[1] 4.391862
> 4.26+(-1.984217*.06645545)
[1] 4.128138



What is the 95% confidence interval for the mean Petal Length in Iris setosa?

mean(setosa$Petal.Length)
[1] 1.462
> qt(.025,49)
[1] -2.009575
> std.err(setosa$Petal.Length)
[1] 0.0245598
> 1.462-(-2.009575*0.0245598)
[1] 1.511355
> 1.462+(-2.009575*0.0245598)
[1] 1.412645


What would be an appropriate 99% confidence interval around the mean of 32, variance of 95, n=20?
Variance----> 95 and n=20......  in order to get STANDARD ERROR: it's sqrt(95)/sqrt(20)

qt(.005,19)
[1] -2.860935
> sqrt(95)/sqrt(20)
[1] 2.179449
> 32-(-2.860935*2.179449)
[1] 38.23526
> 32+(-2.860935*2.179449)
[1] 25.76474


1.3 Testing whether a sample comes from a distribution with known u

mean(setosa$Sepal.Width)
[1] 3.428
> qt(.025,49)
[1] -2.009575
> std.err(setosa$Sepal.Width)
[1] 0.0536078
> 3.428-(-2.009575*0.0536078)
[1] 3.535729
> 3.428+(-2.009575*0.0536078)
[1] 3.320271

So 4cm does not lie within this distirbution, so from a confidence interval it does not lie within here.

Doing it the other way through a T.test:
One Sample t-test

data:  setosa$Sepal.Width
t = -10.6701, df = 49, p-value = 2.237e-14
alternative hypothesis: true mean is not equal to 4
95 percent confidence interval:
 3.320271 3.535729
sample estimates:
mean of x 
    3.428 
    
    1.4 Testing whether 2 means are equal
    
    Frequentist Approach
    use a t-test to assess whether Petal Lengths in iris Setosa differe from those in iris virginica 
    Two Sample t-test

data:  setosa$Petal.Length and virginica$Petal.Length
t = -49.9862, df = 98, p-value < 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -4.252374 -3.927626
sample estimates:
mean of x mean of y 
    1.462     5.552 
    
    
    
    and also do this for virginca and versicolor
    
    Two Sample t-test

data:  versicolor$Petal.Length and virginica$Petal.Length
t = -12.6038, df = 98, p-value < 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -1.495426 -1.088574
sample estimates:
mean of x mean of y 
    4.260     5.552 
    
    YES , BOTH OF THESE GROUPS ARE DIFFERENT.
    
    Calculate a t-stat from scratch
    that<-(mean(setosa$Petal.Length)-mean(virginica$Petal.Length))/sqrt(var(setosa$Petal.Length)/length(setosa$Petal.Length)+var(virginica$Petal.Length)/length(virginica$Petal.Length))
> that
[1] -49.98619
> length(virginica)+length(setosa)-2
[1] 8
> length(virginica)+length(setosa)-2->df
> 2*(1-pt(abs(that),df))
[1] 2.840661e-11

So using a completely different way to calculate a p valuve using a ttest, it still rejects the Null

Do these data satisfy the assumption: yes chosen at random, data are continuous, populations are normally distributed and variances are equal

1.4 Likelihood Approach


llike.twopop <- function(p, X, Y)
    {
        if (p[3]>0) 
            {
                ll.X <- sum(dnorm(X,mean=p[1],sd=p[3],log=T))
                ll.Y <- sum(dnorm(Y,mean=p[2],sd=p[3],log=T))
                -sum(ll.X,ll.Y)
            } else {
                Inf
            }
    }

opt.two <- optim(c(1,1,1),llike.twopop,X=sertosa,Y=virginica)
opt.two$par
opt.two$value

opt.two <- optim(c(1,1,1),llike.twopop,X=setosa$Petal.Length,Y=virginica$Petal.Length)
> opt.two$par
[1] 1.4618647 5.5520878 0.4049793
> opt.two$value
[1] 51.50734

compared this to the likelihood that these the same population was  

opt.one <- optim(c(1,1),llike.onepop,X=setosa$Petal.Length,Y=virginica$Petal.Length)
> opt.one$par
[1] 3.506833 2.084533
> opt.one$value
[1] 215.3572

So the lower number one is the one with the greater likelihood, so these are from 2 different populations. 


I DID THE SAME THING FOR 2 DIFFERENT POPULATIONS


 opt.two <- optim(c(1,1,1),llike.twopop,X=setosa$Petal.Length,Y=virginica$Petal.Length)
> opt.two$par
[1] 1.4618647 5.5520878 0.4049793
> opt.two$value
[1] 51.50734
> llike.onepop <- function(p, X, Y)
+ {
+     if (p[2]>0) 
+     {
+         dat <- c(X,Y)
+         -sum(dnorm(dat,mean=p[1],sd=p[2],log=T))
+     } else {
+         Inf
+     }
+ }
> opt.one <- optim(c(1,1),llike.onepop,X=setosa$Petal.Length,Y=virginica$Petal.Length)
> opt.one$par
[1] 3.506833 2.084533
> opt.one$value
[1] 215.3572


T-test assumptions

qq type plots



par(mFrow=c(1,2))
qqnorm(virginica$Petal.Length)
qqline(virginica$Petal.Length)
qqnorm(versicolor$Petal.Length)
qqline(versicolor$Petal.Length)


sd(virginica$Petal.Length)
sd(versicolor$Petal.Length)

 sd(virginica$Petal.Length)
[1] 0.5518947
> sd(versicolor$Petal.Length)
[1] 0.469911


THEY ARE NOT THE SAME.
  